/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateMail } from './PrivateMail.js';
export * as factories from './factories/index.js';
export { PrivateMail__factory } from './factories/PrivateMail__factory.js';