/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PrivateMail {
      
    export type MessageStruct = {sender: AddressLike, recipient: AddressLike, ciphertext: BytesLike, ciphertextRef: BigNumberish, timestamp: BigNumberish, contentHash: BytesLike}

    export type MessageStructOutput = [sender: string, recipient: string, ciphertext: string, ciphertextRef: bigint, timestamp: bigint, contentHash: string] & {sender: string, recipient: string, ciphertext: string, ciphertextRef: bigint, timestamp: bigint, contentHash: string }
  
    }

  export interface PrivateMailInterface extends Interface {
    getFunction(nameOrSignature: "CIPHER_TEXT_INLINE_MAX" | "MESSAGES_PER_PAGE" | "PREV_PAGE_NONE" | "addressToUsername" | "encryptionPublicKeys" | "getAddressForUsername" | "getLargeCiphertext" | "getMessage" | "getPage" | "getPageWithMessages" | "getPublicKey" | "getRecipientHeadPageId" | "getUsernameHash" | "hasRegisteredKey" | "isRegistered" | "largeCiphertexts" | "messages" | "nextCiphertextRefId" | "nextMessageId" | "nextPageId" | "pages" | "recipientHeadPageId" | "registerPublicKey" | "registerUsername" | "sendMessage" | "usernameOf" | "usernameToAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MessageSent" | "PublicKeyRegistered" | "UsernameRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'CIPHER_TEXT_INLINE_MAX', values?: undefined): string;
encodeFunctionData(functionFragment: 'MESSAGES_PER_PAGE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PREV_PAGE_NONE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addressToUsername', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'encryptionPublicKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAddressForUsername', values: [string]): string;
encodeFunctionData(functionFragment: 'getLargeCiphertext', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMessage', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPage', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPageWithMessages', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPublicKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRecipientHeadPageId', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUsernameHash', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRegisteredKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'largeCiphertexts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'messages', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextCiphertextRefId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextMessageId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextPageId', values?: undefined): string;
encodeFunctionData(functionFragment: 'pages', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recipientHeadPageId', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerPublicKey', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'registerUsername', values: [string]): string;
encodeFunctionData(functionFragment: 'sendMessage', values: [AddressLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'usernameOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usernameToAddress', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'CIPHER_TEXT_INLINE_MAX', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MESSAGES_PER_PAGE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PREV_PAGE_NONE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addressToUsername', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'encryptionPublicKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAddressForUsername', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLargeCiphertext', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPageWithMessages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecipientHeadPageId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUsernameHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRegisteredKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'largeCiphertexts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'messages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextCiphertextRefId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextMessageId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextPageId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recipientHeadPageId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerUsername', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usernameOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usernameToAddress', data: BytesLike): Result;
  }

  
    export namespace MessageSentEvent {
      export type InputTuple = [messageId: BigNumberish, sender: AddressLike, recipient: AddressLike, timestamp: BigNumberish, contentHash: BytesLike];
      export type OutputTuple = [messageId: bigint, sender: string, recipient: string, timestamp: bigint, contentHash: string];
      export interface OutputObject {messageId: bigint, sender: string, recipient: string, timestamp: bigint, contentHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PublicKeyRegisteredEvent {
      export type InputTuple = [owner: AddressLike, pubKey: BytesLike];
      export type OutputTuple = [owner: string, pubKey: string];
      export interface OutputObject {owner: string, pubKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsernameRegisteredEvent {
      export type InputTuple = [owner: AddressLike, username: string];
      export type OutputTuple = [owner: string, username: string];
      export interface OutputObject {owner: string, username: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PrivateMail extends BaseContract {
    
    connect(runner?: ContractRunner | null): PrivateMail;
    waitForDeployment(): Promise<this>;

    interface: PrivateMailInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CIPHER_TEXT_INLINE_MAX: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MESSAGES_PER_PAGE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PREV_PAGE_NONE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addressToUsername: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    encryptionPublicKeys: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    getAddressForUsername: TypedContractMethod<
      [username: string, ],
      [string],
      'view'
    >
    

    
    getLargeCiphertext: TypedContractMethod<
      [refId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getMessage: TypedContractMethod<
      [messageId: BigNumberish, ],
      [PrivateMail.MessageStructOutput],
      'view'
    >
    

    
    getPage: TypedContractMethod<
      [pageId: BigNumberish, ],
      [[bigint[], bigint, bigint] & {messageIds: bigint[], count: bigint, prevPageIdForRecipient: bigint }],
      'view'
    >
    

    
    getPageWithMessages: TypedContractMethod<
      [pageId: BigNumberish, ],
      [[bigint, bigint, PrivateMail.MessageStructOutput[]] & {count: bigint, prevPageIdForRecipient: bigint, pageMessages: PrivateMail.MessageStructOutput[] }],
      'view'
    >
    

    
    getPublicKey: TypedContractMethod<
      [owner: AddressLike, ],
      [string],
      'view'
    >
    

    
    getRecipientHeadPageId: TypedContractMethod<
      [recipient: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUsernameHash: TypedContractMethod<
      [owner: AddressLike, ],
      [string],
      'view'
    >
    

    
    hasRegisteredKey: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [owner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    largeCiphertexts: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    messages: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, string] & {sender: string, recipient: string, ciphertext: string, ciphertextRef: bigint, timestamp: bigint, contentHash: string }],
      'view'
    >
    

    
    nextCiphertextRefId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextMessageId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextPageId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pages: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {count: bigint, prevPageIdForRecipient: bigint }],
      'view'
    >
    

    
    recipientHeadPageId: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    registerPublicKey: TypedContractMethod<
      [pubKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerUsername: TypedContractMethod<
      [username: string, ],
      [void],
      'nonpayable'
    >
    

    
    sendMessage: TypedContractMethod<
      [recipient: AddressLike, ciphertext: BytesLike, contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    usernameOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    usernameToAddress: TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CIPHER_TEXT_INLINE_MAX'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MESSAGES_PER_PAGE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PREV_PAGE_NONE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addressToUsername'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'encryptionPublicKeys'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAddressForUsername'): TypedContractMethod<
      [username: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getLargeCiphertext'): TypedContractMethod<
      [refId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMessage'): TypedContractMethod<
      [messageId: BigNumberish, ],
      [PrivateMail.MessageStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPage'): TypedContractMethod<
      [pageId: BigNumberish, ],
      [[bigint[], bigint, bigint] & {messageIds: bigint[], count: bigint, prevPageIdForRecipient: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPageWithMessages'): TypedContractMethod<
      [pageId: BigNumberish, ],
      [[bigint, bigint, PrivateMail.MessageStructOutput[]] & {count: bigint, prevPageIdForRecipient: bigint, pageMessages: PrivateMail.MessageStructOutput[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getPublicKey'): TypedContractMethod<
      [owner: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRecipientHeadPageId'): TypedContractMethod<
      [recipient: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUsernameHash'): TypedContractMethod<
      [owner: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'hasRegisteredKey'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [owner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'largeCiphertexts'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'messages'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, string] & {sender: string, recipient: string, ciphertext: string, ciphertextRef: bigint, timestamp: bigint, contentHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'nextCiphertextRefId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextMessageId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextPageId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pages'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {count: bigint, prevPageIdForRecipient: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'recipientHeadPageId'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerPublicKey'): TypedContractMethod<
      [pubKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerUsername'): TypedContractMethod<
      [username: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sendMessage'): TypedContractMethod<
      [recipient: AddressLike, ciphertext: BytesLike, contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usernameOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usernameToAddress'): TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >;

    getEvent(key: 'MessageSent'): TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
getEvent(key: 'PublicKeyRegistered'): TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
getEvent(key: 'UsernameRegistered'): TypedContractEvent<UsernameRegisteredEvent.InputTuple, UsernameRegisteredEvent.OutputTuple, UsernameRegisteredEvent.OutputObject>;

    filters: {
      
      'MessageSent(uint256,address,address,uint256,bytes32)': TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
      MessageSent: TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
    

      'PublicKeyRegistered(address,bytes)': TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
      PublicKeyRegistered: TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
    

      'UsernameRegistered(address,string)': TypedContractEvent<UsernameRegisteredEvent.InputTuple, UsernameRegisteredEvent.OutputTuple, UsernameRegisteredEvent.OutputObject>;
      UsernameRegistered: TypedContractEvent<UsernameRegisteredEvent.InputTuple, UsernameRegisteredEvent.OutputTuple, UsernameRegisteredEvent.OutputObject>;
    
    };
  }